# _config.yml
title: 我的电影收藏站 # 你的网站标题
description: >- # 网站描述
  一个展示电影信息和资源链接的个人小站
url: "" # 暂时留空，部署后会自动设置
baseurl: "" # 如果仓库名不是 username.github.io，部署后可能需要设置，现在留空
theme: minima # 使用Jekyll内置的minima主题，简单易用
plugins: # 暂时不需要插件，空着
  - jekyll-feed # minima主题依赖这个，保留
port: 4001  # 添加这行